import {
  Patient,
  PatientInput,
  ClinicalFact,
  ClinicalConflict,
  RecommendedAction,
  HospitalResource,
  AuditEvent,
} from '@/types';

// ==========================================
// SYNTHETIC PATIENT #047 DEMO DATASET
// Note: De-identified synthetic data for clinical intake demonstration
// ==========================================

export const DEMO_PATIENT_047: Patient = {
  id: 'patient_047',
  name: 'Alex Carter',
  age: 24,
  gender: 'Male',
  incidentId: 'MCI-2025-09',
  incidentDescription: 'Road traffic accident',
  arrivalTime: '11:28 AM',
  triageCategory: 'Red (Immediate)',
  primaryComplaint: 'Blunt chest trauma',
  statusDescription: 'Elevated risk of cardiac compromise',
  state: 'CONFLICT_DETECTED',
  severity: 'CRITICAL',
  vitals: {
    heartRate: 128,
    bloodPressure: '86/54 mmHg',
    oxygenSaturation: 92,
    temperature: 36.8,
    respiratoryRate: 26,
  },
  sbar: {
    situation: '24-year-old male, road traffic accident. Unresponsive at scene, now awake but confused.',
    background: 'No known chronic illness. No known allergies (per paramedic).',
    assessment: 'Hypotensive, tachycardic. Suspected internal bleeding.',
    recommendation: 'Urgent imaging and surgical consult. Prepare blood.',
    extractedAt: '2025-09-09T11:32:00.000Z',
  },
  createdAt: '2025-09-09T11:28:00.000Z',
  updatedAt: '2025-09-09T11:42:00.000Z',
};

export const DEMO_INPUTS_047: PatientInput[] = [
  {
    id: 'input_047_triage',
    patientId: 'patient_047',
    type: 'text',
    storagePath: 'notes/triage_note.txt',
    sourceLabel: 'Triage Note (Text)',
    extractedText: 'Intake nurse note: Patient pale, diaphoretic, guarding left hemithorax. Trachea midline. FAST exam pending.',
    uploadedAt: '2025-09-09T11:28:00.000Z',
    processingStatus: 'completed',
  },
  {
    id: 'input_047_audio',
    patientId: 'patient_047',
    type: 'audio',
    storagePath: 'audio/handover_047.wav',
    sourceLabel: 'Paramedic Handover (Audio)',
    extractedText: 'Medic 4 inbound with 24-year-old male involved in high-speed collision. Blunt chest trauma. GCS was 8 at scene, now 13. Vitals: HR 128, BP 86/54. No known allergies per scene report. Suspected internal hemorrhage.',
    uploadedAt: '2025-09-09T11:30:00.000Z',
    processingStatus: 'completed',
  },
  {
    id: 'input_047_history',
    patientId: 'patient_047',
    type: 'image',
    storagePath: 'documents/history_047.jpg',
    sourceLabel: 'Medical History (Image)',
    extractedText: 'PATIENT MEDICAL RECORD: Patient Alex Carter. Confirmed Severe Allergy: PENICILLIN (Anaphylaxis risk). Prior medical condition: Deep Vein Thrombosis (2023) - prescribed ongoing anticoagulant therapy (Warfarin/Apixaban).',
    uploadedAt: '2025-09-09T11:34:00.000Z',
    processingStatus: 'completed',
  },
  {
    id: 'input_047_meds',
    patientId: 'patient_047',
    type: 'image',
    storagePath: 'images/meds_047.jpg',
    sourceLabel: 'Medication (Image)',
    extractedText: 'Prescription Bottle 1: Amoxicillin 500mg capsules (recently filled for dental procedure). Prescription Bottle 2: Apixaban 5mg BID.',
    uploadedAt: '2025-09-09T11:35:00.000Z',
    processingStatus: 'completed',
  },
];

export const DEMO_FACTS_047: ClinicalFact[] = [
  {
    id: 'fact_047_allergy_paramedic',
    patientId: 'patient_047',
    category: 'allergy',
    value: 'No known allergies (per paramedic audio handover)',
    confidence: 90,
    sourceInputIds: ['input_047_audio'],
    verificationStatus: 'UNVERIFIED',
    createdAt: '2025-09-09T11:32:00.000Z',
  },
  {
    id: 'fact_047_allergy_penicillin',
    patientId: 'patient_047',
    category: 'allergy',
    value: 'Severe allergy: Penicillin (risk of anaphylaxis)',
    confidence: 98,
    sourceInputIds: ['input_047_history'],
    verificationStatus: 'VERIFIED',
    createdAt: '2025-09-09T11:34:30.000Z',
  },
  {
    id: 'fact_047_med_amoxicillin',
    patientId: 'patient_047',
    category: 'medication',
    value: 'Prescribed medication: Amoxicillin 500mg',
    confidence: 95,
    sourceInputIds: ['input_047_meds'],
    verificationStatus: 'UNVERIFIED',
    createdAt: '2025-09-09T11:35:30.000Z',
  },
  {
    id: 'fact_047_med_anticoagulant',
    patientId: 'patient_047',
    category: 'medication',
    value: 'History of anticoagulant therapy (Apixaban)',
    confidence: 96,
    sourceInputIds: ['input_047_history', 'input_047_meds'],
    verificationStatus: 'UNVERIFIED',
    createdAt: '2025-09-09T11:35:45.000Z',
  },
  {
    id: 'fact_047_trauma_vitals',
    patientId: 'patient_047',
    category: 'symptom',
    value: 'Blunt chest trauma, hypotension (BP 86/54), tachycardia (HR 128)',
    confidence: 99,
    sourceInputIds: ['input_047_audio', 'input_047_triage'],
    verificationStatus: 'VERIFIED',
    createdAt: '2025-09-09T11:30:15.000Z',
  },
];

export const DEMO_CONFLICTS_047: ClinicalConflict[] = [
  {
    id: 'conflict_047_penicillin',
    patientId: 'patient_047',
    severity: 'critical',
    topic: 'Allergy / Medication Conflict',
    description: 'Penicillin allergy (from medical history) conflicts with Amoxicillin (from medication image).',
    conflictingFactIds: ['fact_047_allergy_penicillin', 'fact_047_med_amoxicillin'],
    requiresHumanReview: true,
    status: 'pending',
    createdAt: '2025-09-09T11:37:00.000Z',
    type: 'conflict',
    tags: ['Allergy', 'Medication', 'Unverified'],
  },
  {
    id: 'conflict_047_anticoagulant',
    patientId: 'patient_047',
    severity: 'high',
    topic: 'High Risk Signal: Bleeding Complication',
    description: 'History of anticoagulant use may be relevant to current trauma and occult hemorrhage.',
    conflictingFactIds: ['fact_047_med_anticoagulant', 'fact_047_trauma_vitals'],
    requiresHumanReview: true,
    status: 'pending',
    createdAt: '2025-09-09T11:37:30.000Z',
    type: 'missed_signal',
    tags: ['Medical History', 'Trauma', 'Unverified'],
  },
];

export const DEMO_ACTIONS_047: RecommendedAction[] = [
  {
    id: 'action_047_bay',
    patientId: 'patient_047',
    priority: 'high',
    action: 'Allocate Trauma Bay',
    rationale: 'Based on severity and current availability (2 bays available).',
    sourceFactIds: ['fact_047_trauma_vitals'],
    requiresHumanApproval: true,
    status: 'pending',
  },
  {
    id: 'action_047_blood',
    patientId: 'patient_047',
    priority: 'high',
    action: 'Prepare Blood Products (O-)',
    rationale: 'Suggested: 2 units PRBC. Patient hypotensive with possible internal bleeding and anticoagulant use.',
    sourceFactIds: ['fact_047_trauma_vitals', 'fact_047_med_anticoagulant'],
    requiresHumanApproval: true,
    status: 'pending',
  },
  {
    id: 'action_047_surgery',
    patientId: 'patient_047',
    priority: 'medium',
    action: 'Surgical Team Alert',
    rationale: 'Early notification recommended for blunt chest trauma with unstable vitals.',
    sourceFactIds: ['fact_047_trauma_vitals'],
    requiresHumanApproval: true,
    status: 'pending',
  },
];

export const DEMO_AUDIT_EVENTS_047: AuditEvent[] = [
  {
    id: 'audit_047_01',
    patientId: 'patient_047',
    type: 'patient_arrived',
    actor: 'system',
    description: 'Patient arrived (MCI-2025-09) and registered at triage intake.',
    createdAt: '2025-09-09T11:28:00.000Z',
  },
  {
    id: 'audit_047_02',
    patientId: 'patient_047',
    type: 'input_uploaded',
    actor: 'clinician',
    description: 'Paramedic audio uploaded: handover_047.wav',
    createdAt: '2025-09-09T11:30:00.000Z',
  },
  {
    id: 'audit_047_03',
    patientId: 'patient_047',
    type: 'analysis_completed',
    actor: 'ai',
    description: 'Audio transcribed & analyzed. Structured SBAR generated.',
    createdAt: '2025-09-09T11:32:00.000Z',
  },
  {
    id: 'audit_047_04',
    patientId: 'patient_047',
    type: 'input_uploaded',
    actor: 'clinician',
    description: 'Medical history image uploaded: history_047.jpg',
    createdAt: '2025-09-09T11:34:00.000Z',
  },
  {
    id: 'audit_047_05',
    patientId: 'patient_047',
    type: 'input_uploaded',
    actor: 'clinician',
    description: 'Medication image uploaded: meds_047.jpg',
    createdAt: '2025-09-09T11:35:00.000Z',
  },
  {
    id: 'audit_047_06',
    patientId: 'patient_047',
    type: 'conflict_detected',
    actor: 'ai',
    description: 'CRITICAL CONFLICT DETECTED: Penicillin allergy from history conflicts with Amoxicillin in medication bottle.',
    createdAt: '2025-09-09T11:37:00.000Z',
  },
  {
    id: 'audit_047_07',
    patientId: 'patient_047',
    type: 'risk_detected',
    actor: 'ai',
    description: 'HIGH RISK SIGNAL: Active anticoagulant therapy identified during blunt chest trauma evaluation.',
    createdAt: '2025-09-09T11:37:30.000Z',
  },
  {
    id: 'audit_047_08',
    patientId: 'patient_047',
    type: 'action_recommended',
    actor: 'ai',
    description: 'Recommendation generated: Allocate Trauma Bay, Prepare Blood Products (O-), Alert Surgical Team.',
    createdAt: '2025-09-09T11:38:00.000Z',
  },
];

export const DEMO_RESOURCES: HospitalResource[] = [
  {
    id: 'res_trauma_bay',
    type: 'trauma_bay',
    name: 'Trauma Bays',
    quantity: 5,
    available: 2,
    location: 'Emergency Resuscitation Wing A',
    updatedAt: '2025-09-09T11:40:00.000Z',
  },
  {
    id: 'res_icu_bed',
    type: 'icu_bed',
    name: 'ICU Beds',
    quantity: 12,
    available: 4,
    location: 'Critical Care Pavilion, 3rd Fl',
    updatedAt: '2025-09-09T11:40:00.000Z',
  },
  {
    id: 'res_blood',
    type: 'blood',
    name: 'O- Blood Units',
    quantity: 10,
    available: 6,
    location: 'Blood Bank Depot A-2',
    updatedAt: '2025-09-09T11:40:00.000Z',
  },
  {
    id: 'res_ventilator',
    type: 'ventilator',
    name: 'Ventilators',
    quantity: 8,
    available: 3,
    location: 'Respiratory Therapy Staging',
    updatedAt: '2025-09-09T11:40:00.000Z',
  },
  {
    id: 'res_or',
    type: 'operating_room',
    name: 'Operating Rooms',
    quantity: 4,
    available: 1,
    location: 'Surgical Suite Complex B',
    updatedAt: '2025-09-09T11:40:00.000Z',
  },
];

export const DEMO_OTHER_PATIENTS: Patient[] = [
  {
    id: 'patient_046',
    name: 'Priya Sharma',
    age: 32,
    gender: 'Female',
    incidentId: 'MCI-2025-09',
    incidentDescription: 'Road traffic accident',
    arrivalTime: '11:20 AM',
    triageCategory: 'Yellow (Delayed)',
    primaryComplaint: 'Closed femur fracture, mild concussion',
    statusDescription: 'Stable vitals, awaiting secondary evaluation',
    state: 'ACTION_PENDING',
    severity: 'WARNING',
    vitals: {
      heartRate: 94,
      bloodPressure: '118/76 mmHg',
      oxygenSaturation: 97,
      temperature: 36.9,
      respiratoryRate: 18,
    },
    createdAt: '2025-09-09T11:20:00.000Z',
    updatedAt: '2025-09-09T11:35:00.000Z',
  },
  {
    id: 'patient_045',
    name: 'Rahul Mehta',
    age: 28,
    gender: 'Male',
    incidentId: 'MCI-2025-09',
    incidentDescription: 'Road traffic accident',
    arrivalTime: '11:15 AM',
    triageCategory: 'Yellow (Delayed)',
    primaryComplaint: 'Deep facial lacerations, shoulder dislocation',
    statusDescription: 'Bleeding controlled, pain management initiated',
    state: 'HUMAN_REVIEW',
    severity: 'WARNING',
    vitals: {
      heartRate: 88,
      bloodPressure: '124/80 mmHg',
      oxygenSaturation: 98,
      temperature: 37.0,
      respiratoryRate: 16,
    },
    createdAt: '2025-09-09T11:15:00.000Z',
    updatedAt: '2025-09-09T11:30:00.000Z',
  },
  {
    id: 'patient_044',
    name: 'Sara Khan',
    age: 19,
    gender: 'Female',
    incidentId: 'MCI-2025-09',
    incidentDescription: 'Road traffic accident',
    arrivalTime: '11:10 AM',
    triageCategory: 'Green (Minimal)',
    primaryComplaint: 'Contusions, minor glass abrasions',
    statusDescription: 'Ambulatory, triage cleared',
    state: 'COMPLETED',
    severity: 'NORMAL',
    vitals: {
      heartRate: 74,
      bloodPressure: '116/72 mmHg',
      oxygenSaturation: 99,
      temperature: 36.6,
      respiratoryRate: 14,
    },
    createdAt: '2025-09-09T11:10:00.000Z',
    updatedAt: '2025-09-09T11:25:00.000Z',
  },
];

